# Generated by Django 4.2.18 on 2025-01-19 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contrato",
            fields=[
                ("id_contrato", models.AutoField(primary_key=True, serialize=False)),
                ("data_emissao", models.DateField(auto_now_add=True)),
                ("data_nascimento_tomador", models.DateField()),
                (
                    "valor_desembolsado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cpf_tomador", models.CharField(max_length=11, unique=True)),
                ("endereco_pais", models.CharField(max_length=50)),
                ("endereco_estado", models.CharField(max_length=50)),
                ("endereco_cidade", models.CharField(max_length=50)),
                ("telefone_tomador", models.CharField(max_length=15)),
                ("taxa_contrato", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Parcela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_parcela", models.IntegerField()),
                ("valor_parcela", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="contrato_api.contrato",
                    ),
                ),
            ],
        ),
    ]
